sudo: required
services:
    - docker

before_install:
    -   docker build -t andreasatle/react-test -f ./client/Dockerfile.dev ./client

script:
    -   docker run -e CI=true andreasatle/react-test npm test

after_sucess:
    -   docker build -t andreasatle/multi-client ./client
    -   docker build -t andreasatle/multi-nginx ./nginx
    -   docker build -t andreasatle/multi-server ./server
    -   docker build -t andreasatle/multi-worker ./worker
    -   echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
    -   docker push andreasatle/multi-client
    -   docker push andreasatle/multi-nginx
    -   docker push andreasatle/multi-server
    -   docker push andreasatle/multi-worker
